name: simple_circular_progress_bar
description: Open source Flutter package, simple circular progress bar (progress indicator).
version: 2.0.0
homepage: https://github.com/Nulllix/simple_circular_progress_bar

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The font is only needed for tests.
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf